language: c

compiler:
  - gcc

before_script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -y
  - sudo apt-get install qemu-kvm -y
  - sudo apt-get install libxen-dev -y
  - sudo apt-get install g++-4.8 -y

env:
  - PLATFORM=hw MACHINE=x86_64 TESTS=qemu EXTRAFLAGS= MYCXX='g++-4.8'
  - PLATFORM=hw MACHINE=i486 ELF=elf TESTS=qemu EXTRAFLAGS='-- -F ACLFLAGS=-m32 -F ACLFLAGS=-march=i686' MYCXX='g++-4.8'
  - PLATFORM=xen MACHINE=x86_64 TESTS=none EXTRAFLAGS= MYCXX='g++-4.8'
  - PLATFORM=xen MACHINE=i486 ELF=elf TESTS=none EXTRAFLAGS='-- -F ACLFLAGS=-m32' MYCXX='g++-4.8'
  - PLATFORM=hw MACHINE=x86_64 TESTS=qemu EXTRAFLAGS= MYCXX='false'
  - PLATFORM=hw MACHINE=x86_64 TESTS=none KERNONLY=-k EXTRAFLAGS= MYCXX='g++-4.8'
  - PLATFORM=xen MACHINE=x86_64 TESTS=none KERNONLY=-k EXTRAFLAGS= MYCXX='g++-4.8'

script:
  - export CC=gcc-4.8
  - export CXX=${MYCXX}
  - git submodule update --init
  - ./build-rr.sh -o myobj -j16 -qq ${KERNONLY} ${PLATFORM} ${EXTRAFLAGS}
  - . ./myobj/config
  - ./tests/buildtests.sh ${KERNONLY}
  - ./tests/runtests.sh ${TESTS}

notifications:
  irc:
    channels:
      - "chat.freenode.net#rumpkernel-builds"
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    skip_join: true
    use_notice: true
  email:
    recipients:
      - rumpkernel-builds@freelists.org
    on_success: always
    on_failure: always

# touch me to force a travis rebuild
